### ISSUE TITLE
安装后运行报错

### ISSUE THREAD

**Issue by lizhan96** [ShixiangWang/install_GISTIC#14]
你好，我使用您提供的安装方法，显示成功安装后我运行run_gistic_example，出现了以下的报错，想请问一下是什么原因。

> $./run_gistic_example 
--- creating output directory ---
--- running GISTIC ---
Setting Matlab MCR root to /data_6t/lizhan/02.software/GISTIC2/MATLAB_Compiler_Runtime
PostVMInit failed to initialize com.mathworks.mwswing.MJStartupForDesktop
PostVMInit failed to initialize com.mathworks.mwswing.MJStartup
java.lang.NoClassDefFoundError: java.awt.Component
	at javax.swing.ImageIcon$2.run(Unknown Source)
	at javax.swing.ImageIcon$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.swing.ImageIcon.createNoPermsComponent(Unknown Source)
	at javax.swing.ImageIcon.access$000(Unknown Source)
	at javax.swing.ImageIcon$1.run(Unknown Source)
	at javax.swing.ImageIcon$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.swing.ImageIcon.<clinit>(Unknown Source)
	at com.mathworks.widgets.desk.Desktop.createContrastingIcon(Desktop.java:183)
	at com.mathworks.widgets.desk.Desktop.<clinit>(Desktop.java:165)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.mathworks.toolstrip.plaf.TSLookAndFeel.install(TSLookAndFeel.java:29)
	at com.mathworks.toolstrip.plaf.TSLookAndFeel.<clinit>(TSLookAndFeel.java:18)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.mathworks.util.PostVMInit$StartupClass.init(PostVMInit.java:108)
	at com.mathworks.util.PostVMInit.perform(PostVMInit.java:132)
PostVMInit failed to initialize com.mathworks.toolstrip.plaf.TSLookAndFeel
MATLAB:hg:set_chck:ExpectedFinitePositive Value must be finite and greater than zero.

**Comment by ShixiangWang** [comment]
你运行 `https://github.com/ShixiangWang/install_GISTIC/blob/master/install_GISTIC2.sh` 安装脚本的结果日志是什么？ 你单独运行这个脚本是否有修改过里面的内容？
